hw2
virusok/reactwork pull request #1
Opened 2024-09-21 01:17 UTC by virusok

дз реакт 2

2024-09-21 07:59 UTC, zubkov7 commented on hw-2/src/main.jsx
> +//console.log(rName); console.log(rMenu); console.log(rReviews);
закоментированный код лучше удалять

2024-09-21 08:02 UTC, zubkov7 commented on hw-2/src/main.jsx
> +  name: rName,
есть ли смысл переименовывать тут, если ниже переопределяете все равно

2024-09-21 08:02 UTC, zubkov7 commented on hw-2/src/main.jsx
> +  name: rName,
сокращенно лучше не именовать переменные, так код хуже читается

2024-09-21 08:04 UTC, zubkov7 requested changes

2024-09-21 08:04 UTC, zubkov7 commented on hw-2/src/main.jsx
> +            {rMenu.map((el,key) => {return (<li key={key}>{el.map(item => item.name)}</li>)})}
в массиве хранятся меню всех ресторанов, а отрисовываются они для одного ресторана. Почему так?

с отзывами аналогично

2024-09-22 05:23 UTC, virusok commented on hw-2/src/main.jsx
> +  name: rName,
+

2024-09-22 05:24 UTC, virusok commented on hw-2/src/main.jsx
> +  name: rName,
+

2024-09-22 05:25 UTC, virusok commented on hw-2/src/main.jsx
> +            {rMenu.map((el,key) => {return (<li key={key}>{el.map(item => item.name)}</li>)})}
Не заметил ошибку во время разработки о не правильном выводе. Переделал.

2024-09-23 10:42 UTC, zubkov7 commented on hw-2/src/main.jsx
> +						{restoraneMenu.map((menu, key) => <li key={key}>{menu.name}</li>)}
вторым параметром в методе map идет index, key в реакте это другое и индекс для этой цели лучше не использовать. Мы будем еще разбирать проп key, пока можно не обращать внимание

2024-09-23 10:44 UTC, zubkov7 commented on hw-2/src/main.jsx
> +      restaurants.map((restorane, key) => {
можно тут применить деструктуризацию `({ name, menu, reviews}) => {})`

еще вы не переписываете значения, поэтому let не нужно использовать. Тут подходит const

2024-09-23 10:44 UTC, zubkov7 commented on hw-2/src/main.jsx
настройте и прогоните prettier еще пожалуйста, чтобы отформатировать код

2024-09-25 11:50 UTC, zubkov7 approved these changes

2024-09-25 14:28 UTC, merged