ДЗ - 3
virusok/reactwork pull request #3
Opened 2024-09-25 14:53 UTC by virusok

1. Переделал ветку репозитория. 
2. Добавлено **дз-3**

2024-09-26 09:25 UTC, zubkov7 commented on homework/src/template/components/App.jsx
> +            <Header/>
давайте сделаем отдельный компонент Layout, как в лекции

2024-09-26 09:26 UTC, zubkov7 commented on homework/src/template/components/restorane/Restorane.jsx
> +export const Index=()=>{
сейчас название компонента не отображает то, что в нем происходит. Подберите название пожалуйста

2024-09-26 09:26 UTC, zubkov7 commented on homework/src/template/components/restorane/Restorane.jsx
> +            return (
давайте вынесем ресторан в отдельный компонент

2024-09-26 09:27 UTC, zubkov7 commented on homework/src/template/components/reviews/Reviews.jsx
> +export const Reviews=({reviewItem})=>{
это 1 отзыв, поэтому Review

2024-09-26 09:28 UTC, zubkov7 requested changes

2024-09-26 09:28 UTC, zubkov7 commented on homework/src/template/js/index.js
в реакте так не пишут, мы еще будем с вами разбирать стилизацию, а для активного ресторана необходимо использовать состояние компонента

2024-09-26 09:29 UTC, zubkov7 commented
настройте прогон prettier пожалуйста для форматирования кода

2024-09-26 12:25 UTC, virusok commented on homework/src/template/components/restorane/Restorane.jsx
> +export const Index=()=>{
fix

2024-09-26 13:15 UTC, virusok commented on homework/src/template/components/reviews/Reviews.jsx
> +export const Reviews=({reviewItem})=>{
fix

2024-09-27 15:15 UTC, virusok commented on homework/src/template/components/App.jsx
> +            <Header/>
fix

2024-09-27 15:15 UTC, virusok commented on homework/src/template/components/restorane/Restorane.jsx
> +            return (
fix

2024-09-27 15:15 UTC, virusok commented on homework/src/template/js/index.js
fix

2024-09-27 15:15 UTC, virusok commented
> настройте прогон prettier пожалуйста для форматирования кода

fix

2024-09-27 15:16 UTC, virusok commented
Исправлены последние ошибки. немного изменил структуру компонентов. мне показалось, что так более логично. Настроил pretter

2024-09-28 09:11 UTC, zubkov7 commented on homework/src/template/components/App.jsx
> +			<Restorane restorane={restorane} />
компонент отображает один ресторан, поэтому ему нужно передавать один ресторан, а не массив. Тут подойдет метод массива find, а не filter

2024-09-28 09:12 UTC, zubkov7 commented on homework/src/template/components/restorane/restoraneitem/RestoraneItem.jsx
> +					<li>{"У ресторана нет меню."}</li>
в таком случае лучше не выводить список, а просто выводить сообщение

2024-09-28 10:01 UTC, virusok commented on homework/src/template/components/App.jsx
> +			<Restorane restorane={restorane} />
fix

2024-09-28 10:01 UTC, virusok commented on homework/src/template/components/restorane/restoraneitem/RestoraneItem.jsx
> +					<li>{"У ресторана нет меню."}</li>
fix

2024-09-29 15:18 UTC, zubkov7 approved these changes

2024-09-30 16:45 UTC, merged